#!/bin/bash

messages=(
    "Linto the wild"
    "Schindler's Lint"
    "Brace yourselves, Linter is coming"
    "Linterstellar"
    "The Lintouchables"
    "La La Lint"
    "James Bond - Lint Another Day"
    "Mission Impossible - Lint protocol"
    "Lintiana Jones and the Last Crusade"
    "La Linta e Bella"
    "The Hobbit: An Unexpected Lint"
    "Sudden Lintpact"
    "The Termilinter"
    "Good Will Linting"
    "Lint Free or Die Hard"
    "The Lintruder"
    "Lost In Translinting"
    "The Flintstones"
    "Men in Black: Linternational"
    "Lint me like one of your French girls"
    "To Lintfinity – and beyond!"
    "Lintglourious Basterds"
    "Lintception"
    "Lintin' in the Rain"
    "Silver Lintings Playbook"
    "The Lintrix"
    "Fifty Shades of Linting"
    "Batman Belints"
    "The Dark Linter"
    "The Dark Linter Returns"
    "The Fellowship of the Linter"
    "The Return of the Linter"
    "Star Linter: A New Warning"
    "Star Linter: The Warnings strike back"
    "Star Linter: Return of the Warnings"
    "Star Linter: The Warning Menace"
    "Star Linter: Attack of the Warnings"
    "Star Linter: Revenge of the Warnings"
    "Star Linter: The Linting Awakens"
    "Star Linter: The Last Warning"
    "Star Linter: The Rise of Warnings"
    "Gone With the Lint"
    "Fantastic Lints and Where to Find Them"
    "Despicable Lint"
    "Lint Runner"
    "Linting Nemo"
    "The Linter Games"
    "The Twilint Saga: Breaking Down"
    "The Wolf of Lint Street"
    "How I Lint Your Mother"
    "Alice in Wonderlint"
    "Snow White and the Linting Dwarfs"
    "Willy Wonka and the Linting Factory"
    "The Linting Mermaid"
    "The Lintcredibles"
    "Stuart Lintle"
)

git commit -m ":rotating_light: ${messages[$RANDOM % ${#messages[@]} ]}"
